In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
import pandas as pd

In [6]:
datos = pd.read_csv('/content/drive/MyDrive/economia_rendimientodeportivo.csv')

In [7]:
print(datos.head())
print(datos.info())
print(datos.describe())

    año  rk    equipo  valor  ingresos  capital_operativo  wins  losses  win%  \
0  2023   1  warriors   7.70     765.0                NaN    44      38  53.7
1  2023   2    knicks   6.60     504.0                NaN    47      35  57.3
2  2023   3    lakers   6.40     516.0                NaN    43      39  52.4
3  2023   4   celtics   4.70     443.0                NaN    57      25  69.5
4  2023   5  clippers   4.65     425.0                NaN    44      38  53.7

   league_rank
0          6.0
1          5.0
2          7.0
3          2.0
4          5.0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   año                180 non-null    int64
 1   rk                 180 non-null    int64
 2   equipo             180 non-null    object
 3   valor              180 non-null    float64
 4   ingresos           30 non-null     float64
 5   capital_operativo  59 non-null     float64
 6   wins               180 non-null    int64
 7   losses             180 non-null    int64
 8   win%               180 non-null    float64
 9   league_rank        178 non-null    float64
dtypes: float64(5), int64(4), object(1)
memory usage: 14.2+ KB
None
               año          rk       valor    ingresos  capital_operativo  \
count   180.000000  180.000000  180.000000   30.000000          59.000000
mean   2020.500000   15.500000    2.427117  352.800000          77.288136
std       1.712589    8.679585    1.268277  105.469525          47.029723
min    2018.000000    1.000000    1.000000  258.000000         -34.000000
25%    2019.000000    8.000000    1.507500  274.000000          43.000000
50%    2020.500000   15.500000    1.987500  327.500000          79.000000
75%    2022.000000   23.000000    3.100000  371.750000          97.500000
max    2023.000000   30.000000    7.700000  765.000000         206.000000

             wins      losses        win%  league_rank
count  180.000000  180.000000  180.000000    178.00000
mean    39.272222   38.888889   49.913333      8.00000
std     11.500221   11.306738   14.046147      4.33746
min     15.000000    9.000000   20.700000      1.00000
25%     31.000000   31.000000   40.200000      4.00000
50%     41.500000   38.000000   51.200000      8.00000
75%     48.000000   46.000000   60.475000     12.00000
max     65.000000   65.000000   79.300000     15.00000

In [8]:
datos_limpios = datos.dropna()

In [11]:
display(datos)

,año,rk,equipo,valor,ingresos,capital_operativo,wins,losses,win%,league_rank
0,2023,1,warriors,7.700,765.0,NaN,44,38,53.7,6.0
1,2023,2,knicks,6.600,504.0,NaN,47,35,57.3,5.0
2,2023,3,lakers,6.400,516.0,NaN,43,39,52.4,7.0
3,2023,4,celtics,4.700,443.0,NaN,57,25,69.5,2.0
4,2023,5,clippers,4.650,425.0,NaN,44,38,53.7,5.0
...,...,...,...,...,...,...,...,...,...,...
175,2018,26,bucks,1.075,NaN,NaN,44,38,53.7,7.0
176,2018,27,timberwolves,1.060,NaN,NaN,47,35,57.3,8.0
177,2018,28,hornets,1.050,NaN,NaN,36,46,43.9,10.0
178,2018,29,grizzlies,1.025,NaN,NaN,22,60,26.8,14.0
179,2018,30,pelicans,1.000,NaN,NaN,48,34,58.5,6.0

In [16]:
columnas_a_eliminar = ['ingresos', 'capital_operativo']
datos_sin_columnas = datos.drop(columnas_a_eliminar, axis=1)

In [17]:
display(datos_sin_columnas)

      año  rk        equipo  valor  wins  losses  win%  league_rank
0    2023   1      warriors  7.700    44      38  53.7          6.0
1    2023   2        knicks  6.600    47      35  57.3          5.0
2    2023   3        lakers  6.400    43      39  52.4          7.0
3    2023   4       celtics  4.700    57      25  69.5          2.0
4    2023   5      clippers  4.650    44      38  53.7          5.0
..    ...  ..           ...    ...   ...     ...   ...          ...
175  2018  26         bucks  1.075    44      38  53.7          7.0
176  2018  27  timberwolves  1.060    47      35  57.3          8.0
177  2018  28       hornets  1.050    36      46  43.9         10.0
178  2018  29     grizzlies  1.025    22      60  26.8         14.0
179  2018  30      pelicans  1.000    48      34  58.5          6.0

[180 rows x 8 columns]

In [18]:
datos_sin_columnas.to_csv('/content/drive/My Drive/base_limpia.csv', index=False)